import PDFDocument from "pdfkit";

import type { BrandProfile, Project, SectionRecord } from "../emovel-ai/types";
import { normalizeExportSections } from "./assembly";

function cleanText(value: unknown) {
  return typeof value === "string" ? value.trim().replace(/\s+/g, " ") : "";
}

function brandLines(brandProfile?: BrandProfile | null) {
  if (!brandProfile) {
    return [];
  }

  return [
    brandProfile.brand_name ? `Brand: ${brandProfile.brand_name}` : "",
    brandProfile.audience ? `Audience: ${brandProfile.audience}` : "",
    brandProfile.tone ? `Tone: ${brandProfile.tone}` : "",
    brandProfile.visual_direction ? `Visual direction: ${brandProfile.visual_direction}` : "",
    brandProfile.offer_positioning ? `Offer positioning: ${brandProfile.offer_positioning}` : "",
  ].filter(Boolean);
}

function collectPdfBuffer(document: PDFKit.PDFDocument) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];

    document.on("data", (chunk: Buffer) => chunks.push(chunk));
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.on("error", reject);
  });
}

export async function generateProjectPdf(input: {
  project: Project;
  sections: SectionRecord[];
  brandProfile?: BrandProfile | null;
  exportedAt?: Date;
}) {
  const exportedAt = input.exportedAt || new Date();
  const normalized = normalizeExportSections(input.sections, input.project.fixed_section_order);
  const document = new PDFDocument({
    size: "A4",
    margin: 56,
    info: {
      Title: cleanText(input.project.name) || "EMOVEL Export",
      Author: "EMOVEL",
      Creator: "EMOVEL",
      Producer: "EMOVEL",
    },
  });
  const bufferPromise = collectPdfBuffer(document);

  document
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor("#9f7a28")
    .text("EMOVEL", { characterSpacing: 2 });
  document.moveDown(0.8);
  document
    .fontSize(26)
    .fillColor("#111111")
    .text(cleanText(input.project.name) || "Untitled Project", { lineGap: 4 });
  document.moveDown(0.4);
  document
    .font("Helvetica")
    .fontSize(9)
    .fillColor("#666666")
    .text(`Exported ${exportedAt.toISOString()}`);
  document.moveDown(1.2);

  const brandContext = brandLines(input.brandProfile);

  if (brandContext.length > 0) {
    document.font("Helvetica-Bold").fontSize(13).fillColor("#111111").text("Brand Context");
    document.moveDown(0.4);
    document.font("Helvetica").fontSize(10).fillColor("#333333");
    brandContext.forEach((line) => document.text(line, { lineGap: 3 }));
    document.moveDown(1);
  }

  if (normalized.warnings.length > 0) {
    document.font("Helvetica-Bold").fontSize(13).fillColor("#111111").text("Export Warning");
    document.moveDown(0.4);
    document.font("Helvetica").fontSize(10).fillColor("#6f4b00");
    normalized.warnings.forEach((warning) => document.text(warning, { lineGap: 3 }));
    document.moveDown(1);
  }

  document.font("Helvetica-Bold").fontSize(13).fillColor("#111111").text("Sections");
  document.moveDown(0.6);

  if (normalized.sections.length === 0) {
    document
      .font("Helvetica")
      .fontSize(11)
      .fillColor("#333333")
      .text("No accepted or ready sections are available for export.", { lineGap: 4 });
  } else {
    normalized.sections.forEach((section, index) => {
      document
        .font("Helvetica-Bold")
        .fontSize(12)
        .fillColor("#111111")
        .text(`${index + 1}. ${section.title}`, { lineGap: 4 });

      if (section.objective) {
        document
          .moveDown(0.25)
          .font("Helvetica")
          .fontSize(10)
          .fillColor("#333333")
          .text(section.objective, { lineGap: 4 });
      }

      document.moveDown(0.9);
    });
  }

  document
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#777777")
    .text("Generated by EMOVEL export system.", 56, 790, { align: "center" });
  document.end();

  return bufferPromise;
}
